source 'https://github.com/gini/gini-podspecs'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'PodsProject' do
	pod 'GiniVision', :git => 'https://github.com/gini/gini-vision-lib-ios.git', :branch => 'PIA-687'
	pod 'GiniVision/Networking', :git => 'https://github.com/gini/gini-vision-lib-ios.git', :branch => 'PIA-687'
end

