using System;
using Foundation;
using ObjCRuntime;
using UIKit;

namespace Binding
{
	// @interface AnalysisResultProxy : NSObject
	[BaseType (typeof(NSObject))]
	[DisableDefaultCtor]
	interface AnalysisResultProxy
	{
		// @property (readonly, copy, nonatomic) NSArray<UIImage *> * _Nonnull images;
		[Export ("images", ArgumentSemantic.Copy)]
		UIImage[] Images { get; }

		// @property (readonly, copy, nonatomic) NSArray<ExtractionProxy *> * _Nonnull extractions;
		[Export ("extractions", ArgumentSemantic.Copy)]
		ExtractionProxy[] Extractions { get; }

		// -(instancetype _Nonnull)initWithExtractions:(NSArray<ExtractionProxy *> * _Nonnull)extractions images:(NSArray<UIImage *> * _Nonnull)images __attribute__((objc_designated_initializer));
		[Export ("initWithExtractions:images:")]
		[DesignatedInitializer]
		IntPtr Constructor (ExtractionProxy[] extractions, UIImage[] images);
	}

	// @interface ExtractionProxy : NSObject
	[BaseType (typeof(NSObject))]
	[DisableDefaultCtor]
	interface ExtractionProxy
	{
		// @property (readonly, copy, nonatomic) NSString * _Nonnull entity;
		[Export ("entity")]
		string Entity { get; }

		// @property (copy, nonatomic) NSString * _Nonnull value;
		[Export ("value")]
		string Value { get; set; }

		// @property (copy, nonatomic) NSString * _Nullable name;
		[NullAllowed, Export ("name")]
		string Name { get; set; }

		// -(instancetype _Nonnull)initWithEntity:(NSString * _Nonnull)entity value:(NSString * _Nonnull)value name:(NSString * _Nullable)name __attribute__((objc_designated_initializer));
		[Export ("initWithEntity:value:name:")]
		[DesignatedInitializer]
		IntPtr Constructor (string entity, string value, [NullAllowed] string name);
	}

	// @interface GVLProxy : NSObject
	[BaseType (typeof(NSObject))]
	[DisableDefaultCtor]
	interface GVLProxy
	{
		// @property (readonly, nonatomic, strong) UIViewController * _Nonnull viewController;
		[Export ("viewController", ArgumentSemantic.Strong)]
		UIViewController ViewController { get; }

		// -(instancetype _Nonnull)initWithDomain:(NSString * _Nonnull)domain id:(NSString * _Nonnull)id secret:(NSString * _Nonnull)secret delegate:(id<GVLProxyDelegate> _Nonnull)delegate __attribute__((objc_designated_initializer));
		[Export ("initWithDomain:id:secret:delegate:")]
		[DesignatedInitializer]
		IntPtr Constructor (string domain, string id, string secret, GVLProxyDelegate @delegate);
	}

	// @protocol GVLProxyDelegate
	[Protocol, Model (AutoGeneratedName = true)]
	interface GVLProxyDelegate
	{
		// @required -(void)giniVisionAnalysisDidFinishWithResult:(AnalysisResultProxy * _Nonnull)result;
		[Abstract]
		[Export ("giniVisionAnalysisDidFinishWithResult:")]
		void GiniVisionAnalysisDidFinishWithResult (AnalysisResultProxy result);

		// @required -(void)giniVisionAnalysisDidFinishWithoutResults:(BOOL)showingNoResultsScreen;
		[Abstract]
		[Export ("giniVisionAnalysisDidFinishWithoutResults:")]
		void GiniVisionAnalysisDidFinishWithoutResults (bool showingNoResultsScreen);

		// @required -(void)giniVisionDidCancelAnalysis;
		[Abstract]
		[Export ("giniVisionDidCancelAnalysis")]
		void GiniVisionDidCancelAnalysis ();
	}

	// @interface GiniSDKProxy : NSObject
	[BaseType (typeof(NSObject))]
	[DisableDefaultCtor]
	interface GiniSDKProxy
	{
		// -(instancetype _Nonnull)initWithId:(NSString * _Nonnull)id secret:(NSString * _Nonnull)secret domain:(NSString * _Nonnull)domain __attribute__((objc_designated_initializer));
		[Export ("initWithId:secret:domain:")]
		[DesignatedInitializer]
		IntPtr Constructor (string id, string secret, string domain);

		// -(void)removeStoredCredentials;
		[Export ("removeStoredCredentials")]
		void RemoveStoredCredentials ();
	}
}
